version: "3.8"

services:
  # ---------- BD Oracle ----------
  oracle:
    image: gvenzl/oracle-xe:11-slim
    container_name: oracle-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - ./db/init:/container-entrypoint-initdb.d
    environment:
      ORACLE_PASSWORD: root
      APP_USER: app_user
      APP_USER_PASSWORD: app_pass
      TZ: UTC                                # <-- opcional, por coherencia
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'select 1 from dual;' | sqlplus -s system/root@localhost:1521/XE || exit 1",
        ]
      interval: 20s
      retries: 10

  # ---------- API Spring Boot ----------
  commerce:
    build:
      context: ./commerce-service            # carpeta del Dockerfile
      dockerfile: Dockerfile
    container_name: commerce-service
    ports:
      - "8080:8080"
    depends_on:
      oracle:
        condition: service_healthy           # espera a que Oracle esté sano
    environment:
      # --- FIX de zona horaria ------------
      TZ: UTC                                # la hora del contenedor
      JAVA_TOOL_OPTIONS: >-
        -Duser.timezone=UTC
        -Doracle.jdbc.timezoneAsRegion=false
      # ------------------------------------

      # Conexión JDBC (añadimos el flag también en la URL por si acaso)
      SPRING_DATASOURCE_URL: >-
        jdbc:oracle:thin:@//oracle:1521/XE?oracle.jdbc.timezoneAsRegion=false
      SPRING_DATASOURCE_USERNAME: comercio
      SPRING_DATASOURCE_PASSWORD: comercio_pwd
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
      

      # Configuración JPA
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_OPEN_IN_VIEW: false
      SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE: UTC
      # Dialecto (opcional, pero ayuda a Hibernate)
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.Oracle10gDialect


      # JWT
      JWT_SECRET: "WbnvG95TOhefpuF1ERbQkUSt2SxkRADkkes6/T27Wk44P0+xSm0OmAePw/iViE4n77/KKDimn3HKHrp96PilVA=="

      JWT_EXPIRATION_MINUTES: 60

    restart: unless-stopped                  # reinicia si algo falla

networks:
  default:
    name: prueba-net
